class CONSTANTS
    MAX_BOOKS_TO_BE_ISSUED = 5
    MAX_LENDING_DAYS = 10
end

class RESERVATION_STATUS
    OPEN, AVAILABLE, COMPLETED, CANCLED = 1, 2, 3, 4
end

class LENDING_STATUS
    ACTIVE, RETURNED, RENEWED, DUE = 1,2,3,4
end